[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    ui: UI-тесты
    courses: Маркировка для тестов, связанных с курсами.
    regression: Маркировка для регрессионных тестов.
    dashboard: Маркировка тестов, связанных с рабочей панелью
    authorization: Маркировка тестов, связанных с авторизацией